spring:
    datasource:
        url: jdbc:mysql://${DATABASE_HOST}:3306/review?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
        username: ${DATABASE_USER}
        password: ${DATABASE_PASSWORD}
        driver-class-name: com.mysql.cj.jdbc.Driver
    application:
      name: review

mybatis-plus:
    global-config:
        db-config:
            logic-delete-field: isDelete
            logic-delete-value: 1
            logic-not-delete-value: 0
