spring:
    datasource:
        url: jdbc:mysql://${DATABASE_HOST:database-review.c3iecqyyk6er.us-west-2.rds.amazonaws.com}:3306/review?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
        username: ${DATABASE_USER:admin}
        password: ${DATABASE_PASSWORD:Aptx4869}
        driver-class-name: com.mysql.cj.jdbc.Driver
    application:
      name: review

mybatis-plus:
    global-config:
        db-config:
            logic-delete-field: isDelete
            logic-delete-value: 1
            logic-not-delete-value: 0
