apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-review-deployment
spec:
  selector:
    matchLabels:
      app: review
  replicas: 3
  template:
    metadata:
      labels:
        app: review
    spec:
      containers:
        - name: review
          image: 767398101426.dkr.ecr.us-west-2.amazonaws.com/review:1.0
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: spring-review-config
          resources:
            requests:
              cpu: 200m